### ISSUE TITLE
Cannot play podcasts

### ISSUE THREAD

**Issue by khers** [CappielloAntonio/tempo#45] opened 2023-08-22 20:28 UTC
I am trying Tempo for the first time so I might have configured something incorrectly but I cannot get podcasts to play at all. Tempo can navigate the feeds on my Airsonic-advanced server just fine and it has no problem playing music from the same server.

When I click the play button next to an episode it takes me to the playing screen but nothing happens and the logs on my server suggest that the audio was never requested.

**Comment by CappielloAntonio** [comment] 2023-08-23 12:41
Hello and thanks for reporting! 

Apparently Airsonic handles podcas differently than Gonic, with which I did the tests and made sure they worked. I've now put up an Airsonic instance locally and am running some tests. I was able to reproduce the bug, now I'm going to work on fixing it.

**Comment by khers** [comment] 2023-08-23 15:11
If it makes a difference, I am running this fork: https://github.com/kagemomiji/airsonic-advanced as the main airsonic and airsonic-advanced seem to be as dead as subsonic.

**Comment by CappielloAntonio** [comment] 2023-08-24 08:10
Nice find! 

Having only used Gonic and the Subsonic demo instance for podcast tests, I had never noticed that the streamId was used for the podcast streams and not the simple Id.

Anyway, the problem is now fixed.

**Closed by CappielloAntonio** 2023-08-24 08:10 UTC
Labels: bug
