### ISSUE TITLE
[Feature Request] - Remember podcast progress

### ISSUE THREAD

**Issue by Cambi0nn** [CappielloAntonio/tempo#98] opened 2023-10-11 17:37 UTC
## Summary
Remember progress of podcast episodes.

## Description
Currently the podcast feature doesn't seem to remember progress of episodes. Because of this, when switching between music and podcasts, you'll have to continously remember or search back where you where.

Preffered solution would be to just start where I left off. Depending on possibilities tinestamps could be synchronised trough Subsonic API or stored locally in cache.

## Use Case
When listening to a podcast but taking a break. Switching to listen to music or another podcast episode, to later go back to the podcast and just continue from where you were.

## Additional context
N/A

**Comment by CappielloAntonio** [comment] 2023-10-11 18:51
I am closing this issue, as it is the duplicate of issue #79

**Closed by CappielloAntonio** 2023-10-11 18:51 UTC
