### ISSUE TITLE
Selecting "Library" causes Tempo to halt

### ISSUE THREAD

**Issue by c0utta** [CappielloAntonio/tempo#15] opened 2023-07-12 13:46 UTC
Pixel Pro 7.

Was hoping the latest version fixed this, but unfortunately no.

Selecting "Library" causes "Tempo keeps stopping" - I have not been able to see the library view yet!

How can I help isolate this issue?

Cheers

**Comment by c0utta** [comment] 2023-07-18 10:37
Hi Antonio,

At this stage I’m happy to run an unsigned version – just let me know what you’d like me to do.

Cheers

**Comment by CappielloAntonio** [comment] 2023-07-18 12:36
So, I just uploaded a debug version of the app, you can find it in the Release section. 
Do you know how to capture a crash log? 
Do you have ADB installed on your machine?

**Comment by c0utta** [comment] 2023-07-18 12:48
Downloaded and installed (had to remove the old version of Tempo)
Have never captured a crash log.
Never heard of ADB until now.

Although I’m in IT, this is new ground for me.

Cheers

**Comment by c0utta** [comment] 2023-07-19 14:46
Wow, way past me since I don't have my own PC.

Next (or last) resort is access to my server.  Happy to do this, just need a secure method to transfer login details.

Cheers

**Comment by CappielloAntonio** [comment] 2023-07-20 07:33
Hi @c0utta, thanks for your help.
Could you try this new version of the app?
If there are no further problems, you can delete my user from the server.

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12103245/app-tempo-debug.zip)

(apk files are not supported so I've zipped it and uploaded as a zip file)

**Comment by c0utta** [comment] 2023-07-20 10:57
Yes, this version works.

I will keep your access open, just in case....

________________________________

**Comment by CappielloAntonio** [comment] 2023-07-20 11:36
Okay, thanks a lot and again, thanks for your cooperation! 
I'm closing this issue now but feel free to reopen it should there be other problems or open a new one.

**Comment by make-42** [comment] 2023-08-28 17:49
I seem to be experiencing the same issue

**Comment by make-42** [comment] 2023-08-28 17:52
I'm using a Google Pixel 6 Pro on Android 14 (UPB5.230623.005). I've tried the APK on F-Droid, the APK in this thread and the latest CI build.

**Comment by make-42** [comment] 2023-08-28 22:11
For some reason tapping scan library in the settings makes this issue go away...

**Comment by make-42** [comment] 2023-08-28 22:11
However it does still crash when playing a track

**Comment by CappielloAntonio** [comment] 2023-08-29 06:06
Hi @make-42, would it be possible for you to capture a crash log? Alternatively, would it be possible to have access credentials, even for a demo user, in order to reproduce the problem as quickly as possible?

**Comment by make-42** [comment] 2023-08-29 17:32
Well, in the meantime I changed from Subsonic to Navidrome and it now works fine (I just figured this out using your APK because I used Ultrasonic for testing Navidrome. The issue is with me using Subsonic. If you want me to host my Subsonic instance again for you you to try to debug I can do that.

**Comment by CappielloAntonio** [comment] 2023-08-30 07:51
If that's okay with you, we could put the Subsonic instance back up and fix the bug. We would be doing a favor to those who still use Subsonic.

Tell me when I can send you my "trash" email so you can pass me the login credentials for a demo user. In case you need to create it, please make sure the error repeats and tell me how I can reproduce it.

**Comment by make-42** [comment] 2023-08-30 14:13
That's okay with me. You can send your email address to ontake@ontake.dev and the instance will be up at https://music.ontake.dev the issue only happens when playing a FLAC file from what I can understand.

**Comment by make-42** [comment] 2023-08-30 14:21
To reproduce: Using Android 14 (Google Pixel Beta) open Tempo, log-on and play a track. It crashes.

**Comment by CappielloAntonio** [comment] 2023-08-30 14:24
Email sent!

**Comment by CappielloAntonio** [comment] 2023-08-30 15:51
I'm publishing a new version of the app in pre-release, maybe you can test it with me too.

May I ask if the version of Tempo that had problems was downloaded from F-Droid using IzzyDroid's repositories? If so, when did you download that version?

I'm trying to reproduce the problem using the latest v3.5.3 release (whether signed for release on GitHub or not) but I can't. I can easily navigate the Library section and play any file. Could you possibly test that the problem also occurs with the test account?

Could it be that the problem occurred with versions of the app prior to the one released on August 25th? With the latest version published here on GitHub does the problem reoccur on Subsonic?

**Comment by make-42** [comment] 2023-08-30 16:21
It was downloaded using IzzyDroid's repositories. It's version 3.4.6. It works fine using the latest v3.5.3 release.

**Comment by make-42** [comment] 2023-08-30 16:22
Which is very weird. I even thought I tried the CI build too...

**Comment by make-42** [comment] 2023-08-30 16:23
Man what...

**Comment by CappielloAntonio** [comment] 2023-08-31 06:35
IzzyDroid probably hadn't updated to the latest version yet when you downloaded the app. Just for the latest version, a couple of fairly important bugs that caused the app to crash had also been fixed.
If a similar bug reappears, feel free to reopen the issue or create a new one.

**Closed by CappielloAntonio** 2023-08-31 06:35 UTC
Labels: bug

**Comment by make-42** [comment] 2023-08-31 09:23
Yes. Thank you very much for your time.
