### ISSUE TITLE
[BUG] - Albums from same year don't get sorted correctly

### ISSUE THREAD

**Issue by Cambi0nn** [CappielloAntonio/tempo#87] opened 2023-09-18 06:14 UTC
## Describe the bug
Albums released in the same year are sorted by alfabet, not exact date, despige these tags being available.

## Expected behavior
When a full date (including month and day) is present in the metadata, sort on that above alfabetical sort.

## To Reproduce
Add 2 albums under the same artist with different release dates, but withing the same year. For example: 2023-01-25 and 2023-08-14. Make sure the later album starts with a letter earlier in the alfabet than the 1st. You will see that on the artist page, the 2nd album is placed in front of the 1st.

## Environment
 - Android device: Sony Xperia 1 IV
 - Android OS version: 13
 - App version: 3.5.7
 - Other relevant details: N/A

## Logs or Screenshots
N/A

## Additional context
N/A

**Comment by CappielloAntonio** [comment] 2023-09-30 09:22
Hi @Cambi0nn this is not a bug regarding my app, but a limitation of the subsonic API which returns me the year intended as a Int and not as a date. Unfortunately I cannot make any further distinction.

**Comment by CappielloAntonio** [comment] 2023-10-11 20:30
I don't think there's much I can do with the Subsonic API as it stands, so I'll close this issue.

**Closed by CappielloAntonio** 2023-10-11 20:30 UTC
