### ISSUE TITLE
How to view/play not yet downloaded podcast episodes

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#18] opened 2023-07-25 21:17 UTC
I'm not sure if this is a server-side or client-side issue, or intended behavior in *sonic

I'm using Gonic. If I add a podcast RSS feed URL into it, it can only download ALL existing episodes, or download the latest one when it's been published.

If I don't download all the existing episodes, I see nothing in Tempo when I select the podcast. I have to download episodes for them to appear in Tempo.

**Comment by CappielloAntonio** [comment] 2023-07-27 13:40
Hello, here I would like to ask users help and advice. 

Gonic for example, once a channel has been added, allows you to see all the episodes of a podcast, whether they have been downloaded or not. This does not mean that the not-downloaded episodes were playable, but they are still listed to me. 

When viewing the episodes on the page dedicated to the channel, I hid the unplayable episodes as they slowed down the interface (I don't get the episodes in a paginated way) and would only be a dead weight for the user. They are there, but it's as if they weren't there because they cannot be reproduced.

I think I made the right choice by hiding the episodes the user can't listen to, what do you think?

**Comment by molohov** [comment] 2023-07-27 13:43
Maybe this could be a setting in Tempo, allowing the user to decide this behavior

**Comment by CappielloAntonio** [comment] 2023-07-27 13:51
Right, but I should limit item creation to a preset number (25/50/100) because there is no way to ask the server to give me the first page of 10 items, the second page of 10 items and so on. [The ones I have available are not paginated results.](http://www.subsonic.org/pages/api.jsp#getPodcasts)

So between being able to choose to see 100 episodes slowly, of which only a part can be played, and seeing all the episodes that the user can play at that moment, I chose the latter.

I'll think about it though, I might try something on that.

**Comment by molohov** [comment] 2023-07-27 14:02
Are you aware of other sonic servers that download more episodes, or provide options for downloading specific episodes? Gonic extremely minimal in this regard

**Comment by CappielloAntonio** [comment] 2023-07-27 14:05
Unfortunately not, my two reference servers are Navidrome and Gonic.  
Maybe some other user can help you with this.

**Comment by CappielloAntonio** [comment] 2023-07-30 14:20
Hi @molohov, I've made a few steps forward regarding viewing undownloaded episodes.

If you want you can try this new version of the app:

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12209398/app-tempo-debug.zip)

**Comment by molohov** [comment] 2023-07-30 22:49
Installed and tried out the filter option. It doesn't seem to be able to play non downloaded episodes? I assumed this would trigger the server to do so?

**Comment by CappielloAntonio** [comment] 2023-07-31 08:25
Now you can request the server to download an episode that has not yet been downloaded.
This functionality will be introduced starting from the next version of the app, but if you want to try it in preview I can build a test apk.

**Closed by CappielloAntonio** 2023-07-31 08:25 UTC
