### ISSUE TITLE
Seek bar is broken when transcoding

### ISSUE THREAD

**Issue by OhaDerErste** [CappielloAntonio/tempo#75] opened 2023-09-12 16:00 UTC
(See screenshot below)  

![Screenshot_20230912-175612_Tempo](https://github.com/CappielloAntonio/tempo/assets/77100649/9cda7c5d-c6f9-411b-bd03-afcbf80bfea5)
I'm on stock LineageOS 20 if that matters

**Comment by GallowsDove** [comment] 2023-09-16 09:19
Hey! Could you please elaborate on when this happens? What server are you using? What steps can be taken to replicate this?

**Comment by CappielloAntonio** [comment] 2023-09-16 09:29
The bug is easily reproducible, just start music playback with transcoding or use Airsonic Advanced.  It seems that on these two occasions the server does not send information on the duration of the file as happens when the file is original and only inserts it when it reaches the end of playback, when the transmission of the file is complete.  An annoying problem for sure, which has already been encountered by another user previously with podcasts.

**Comment by GallowsDove** [comment] 2023-09-16 14:20
That's why I wanted to know whether this is the same issue, in which case I believe this issue should be closed to avoid tracking the same problem within several issues.

**Comment by CappielloAntonio** [comment] 2023-09-16 14:26
Technically the problems are different, the cause may (not necessarily) be the same. The final effect however in both situations is the user's inability to use the seekbar.
I changed the issue title to track this specific case.

**Comment by GallowsDove** [comment] 2023-09-16 15:52
It seems that for Navidrome it helps setting "&estimateContentLength=true" in stream URI, but this requires more testing with more servers. I don't have other servers set up, could you please try it out @CappielloAntonio?

**Comment by CappielloAntonio** [comment] 2023-09-17 10:06
Hey @GallowsDove with this way we solve with Navidrome, but all the other servers remain.

Anyway, have you tried it? What do you think about it? It actually works, but the waiting times before the track starts are considerably longer. 

However, we have limited the problem, confirming what was already thought that the server is not sending the duration of the track in the first chunks of the file.

**Comment by CappielloAntonio** [comment] 2023-09-17 10:10
But take a look at this thread on [Reddit](https://www.reddit.com/r/navidrome/comments/imdlt7/ffmpeg_questionissue/
).

To quote deluan:

> When the file is being transcoded on the fly, clients usually do not show the track length. This is true for all music servers AFAIK. There's nothing much you can do about it.
> 
> Lengthy tracks will keep the CPU busy longer, but in general should not crash the RPi. I can't give more insights here as I don't have a RPi. You could try using Opus, maybe the transcoding is lighter, not sure.
> 
> Navidrome caches the transcoded files, so next time you play a song that was recently transcoded, it should not do it again, and the track will behave as a normal track (showing the track length and with no CPU spikes)

**Comment by CappielloAntonio** [comment] 2023-09-17 10:22
You know what, `&estimateContentLength=true` might not be a bad idea, it should also be included as a setting that the user can choose to activate (warning the user that the waiting times between one track and another might get longer especially when next is pushed repeatedly). 

I'm testing with multiple servers, but I could possibly need a hand from the users.

It seems to be a [well-established practice](https://github.com/search?q=%26estimateContentLength%3Dtrue&type=code) then.

**Comment by GallowsDove** [comment] 2023-09-17 12:10
For now it seems like a good idea to put it as an optional switch in settings, at least until a better solution can be figured out.

**Comment by CappielloAntonio** [comment] 2023-09-17 17:23
Hi @OhaDerErste, I added the ability to request the server to estimate the duration of the file being transcoded. Can you try with the new version of the app that has just been released?

**Comment by OhaDerErste** [comment] 2023-09-17 18:03
Just tried it out and it isnt broken anymore but the transcoding info on the top of the screen is gone

**Comment by GallowsDove** [comment] 2023-09-17 18:35
> Just tried it out and it isnt broken anymore but the transcoding info on the top of the screen is gone

I believe that had issues before that when I was testing stuff, it would be nice to make a new issue about that.

**Comment by CappielloAntonio** [comment] 2023-09-17 19:06
I can confirm that the transcoding information will no longer be displayed in the foreground as it is potentially misleading. If only the object of the track being played contained within it the transcoding information, everything would be easier, and it's a shame because the properties are inside the Child object, but they are not used.

Previously the transcoding information was taken from the user's preferences, but if the server did not support those certain parameters it would ignore the transcoding, but the user would still continue to see the symbol and the transcoding information.

I thought I'd solve it with an information dialog where there's all the information contained in the Child object. If in the future they start to be used the transcoding parameters will be shown there.

Anyway, thanks again @GallowsDove for the precious help, and I'll close this issue now.

**Closed by CappielloAntonio** 2023-09-17 19:06 UTC
