### ISSUE TITLE
[BUG] - Podcast not work with Music App in Nextcloud Server (subsonic)

### ISSUE THREAD

**Issue by guifuentes8** [CappielloAntonio/tempo#244] opened 2024-05-20 22:38 UTC
## Describe the bug
I integrated subsonic api using my self hosted Nextcloud (music app) in Tempo app, but podcasts can't run when i press the button play on my device. Musics work normal.

## Expected behavior
When i click in play button, i expect to play the podcast (maybe the same as #45, for nextcloud music app in the case).

## To Reproduce
1 - Have a nextcloud server
2 - Add music app in nextcloud server
3 - Add podcasts rss in circle red like screenshot below.
4 - Integrate subsonic api with Tempo like screenshot black rectangle.
5 - Click podcast tab and play some podcast.

## Environment
 - Android device: Samsung Galaxy m13
 - Android OS version: 14
 - App version: 3.8.1 ( tested with F-droid and release apk here Github) 
 - Other relevant details: I am using nextcloud with tailscale (private VPN), but my musics in nextcloud server is playing normal in Tempo, the bug only occurs for playing podcasts. I tested with 2 podcasts and in other app (Ultrasonic, it works). Probably is something wrong with integration. 

## Logs or Screenshots
![image](https://github.com/CappielloAntonio/tempo/assets/65429509/fc1399b8-b949-437d-a110-7b6ce6f799f7)

## Additional context
Ultrasonic app works normally with sames configs describe before... I think the problem is in Tempo app.

I love Tempo app, awesome project! Thank you <3

**Comment by CappielloAntonio** [comment] 2024-05-25 17:16
Hi @guifuentes8,
I downloaded and installed a Nextcloud instance and installed Music as you described. 

The problem you were having was caused by a redirect from your server to the actual uri of the podcast.

I solved it, I can send you a test version of the app to try. The fix will be released with the next app version.

**Comment by guifuentes8** [comment] 2024-05-25 19:14
Thank you! Nice!

Please, send me a test version, i want to try! If everything works fine, i will close this PR.

**Comment by CappielloAntonio** [comment] 2024-05-25 20:53
Okay, then I'll send you the f-droid version. If I sent you the Github version you would be forced to delete your current version because the app signature would change but the package name would be the same.
Let me know if the problem is solved.

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/15445004/app-notquitemy-debug.zip)

**Closed by CappielloAntonio** 2024-05-25 20:53 UTC

**Comment by guifuentes8** [comment] 2024-05-25 21:36
I test in my phone, its works fine! Excelent! Tempo app is so cool <3

Thank you @CappielloAntonio for quickly response and fix the bug. Have a nice day!
